From openjdk:8
Expose 8090
Add sourceCode/cicdPrototype/cicdProj/target/complaintredressalsystem-0.0.1-snapshot.war complaintredressalsystem-0.0.1-snapshot.war
ENTRYPOINT ["java","-jar","/complaintredressalsystem-0.0.1-snapshot.war"]